# Generated by Django 5.1 on 2024-08-20 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_bloglikedbyuser_blog_post_bloglikedbyuser_is_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloglikedbyuser",
            name="blog_post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="liked_blogs",
                to="api.blogpost",
            ),
        ),
    ]
