# Generated by Django 5.1 on 2024-08-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_bloglikedbyuser_blog_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloglikedbyuser",
            name="name",
            field=models.CharField(max_length=20),
        ),
    ]
