# Generated by Django 5.1 on 2024-08-20 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_bloglikedbyuser_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="publisher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detailed_post",
                to="api.publisher",
            ),
        ),
    ]
