# Generated by Django 5.1 on 2024-08-20 07:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_blogpost_publisher"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloglikedbyuser",
            name="liked_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
